name: Proxy Auto Checker

on:
  schedule:
    - cron: '0 0 * * *' # Chạy vào 00:00 mỗi ngày
  workflow_dispatch:

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests proxy-checker[socks]

      - name: Run proxy checker
        run: python checker.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update working proxies"
          title: "Daily Proxy Update"
          body: "This PR contains the latest working proxies checked automatically."
          branch: proxy-update
          delete-branch: true
